apiVersion: v1
kind: Service
metadata:
  name: "service-{{ .Values.service.name }}"
  namespace: {{ .Values.service.namespace }}
  annotations:
   alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.healthcheck.endpoint }}
spec:
  selector:
    app: "{{ .Values.service.name }}"
  ports:
    - name: http
      port: {{.Values.ports.serviceport}}
      targetPort: {{ .Values.ports.containerport }}